/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionIndexRouteImport } from './routes/$section/index'
import { Route as SectionSlugRouteImport } from './routes/$section/$slug'
import { Route as SectionSubsectionSlugRouteImport } from './routes/$section/$subsection/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionIndexRoute = SectionIndexRouteImport.update({
  id: '/$section/',
  path: '/$section/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSlugRoute = SectionSlugRouteImport.update({
  id: '/$section/$slug',
  path: '/$section/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSubsectionSlugRoute = SectionSubsectionSlugRouteImport.update({
  id: '/$section/$subsection/$slug',
  path: '/$section/$subsection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$section/$slug': typeof SectionSlugRoute
  '/$section/': typeof SectionIndexRoute
  '/$section/$subsection/$slug': typeof SectionSubsectionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$section/$slug': typeof SectionSlugRoute
  '/$section': typeof SectionIndexRoute
  '/$section/$subsection/$slug': typeof SectionSubsectionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$section/$slug': typeof SectionSlugRoute
  '/$section/': typeof SectionIndexRoute
  '/$section/$subsection/$slug': typeof SectionSubsectionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$section/$slug'
    | '/$section/'
    | '/$section/$subsection/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$section/$slug' | '/$section' | '/$section/$subsection/$slug'
  id:
    | '__root__'
    | '/'
    | '/$section/$slug'
    | '/$section/'
    | '/$section/$subsection/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionSlugRoute: typeof SectionSlugRoute
  SectionIndexRoute: typeof SectionIndexRoute
  SectionSubsectionSlugRoute: typeof SectionSubsectionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section/': {
      id: '/$section/'
      path: '/$section'
      fullPath: '/$section/'
      preLoaderRoute: typeof SectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section/$slug': {
      id: '/$section/$slug'
      path: '/$section/$slug'
      fullPath: '/$section/$slug'
      preLoaderRoute: typeof SectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section/$subsection/$slug': {
      id: '/$section/$subsection/$slug'
      path: '/$section/$subsection/$slug'
      fullPath: '/$section/$subsection/$slug'
      preLoaderRoute: typeof SectionSubsectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionSlugRoute: SectionSlugRoute,
  SectionIndexRoute: SectionIndexRoute,
  SectionSubsectionSlugRoute: SectionSubsectionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
